export const bandeiras = {
  ARG: require("./assets/jogos/argentina.png"),
  AUS: require("./assets/jogos/australia.png"),
  BRA: require("./assets/jogos/brazil.png"),
  CAN: require("./assets/jogos/canada.png"),
  COL: require("./assets/jogos/colombia.png"),
  CZE: require("./assets/jogos/czech republic.png"),
  ENG: require("./assets/jogos/england.png"),
  ESP: require("./assets/jogos/spain.png"),
  FRA: require("./assets/jogos/france.png"),
  GER: require("./assets/jogos/germany.png"),
  JPN: require("./assets/jogos/japan.png"),
  KOR: require("./assets/jogos/south korea.png"),
  MAR: require("./assets/jogos/morocco.png"),
  MEX: require("./assets/jogos/mexico.png"),
  POR: require("./assets/jogos/portugal.png"),
  RSA: require("./assets/jogos/south africa.png"),
  URU: require("./assets/jogos/uruguay.png"),
  USA: require("./assets/jogos/united states.png"),
  ALG: require("./assets/jogos/algeria.png"),
  AUT: require("./assets/jogos/austria.png"),
  BEL: require("./assets/jogos/belgium.png"),
  CRO: require("./assets/jogos/croatia.png"),
  NED: require("./assets/jogos/netherlands.png"),
  SEN: require("./assets/jogos/senegal.png"),
  SUI: require("./assets/jogos/switzerland.png"),
  BIH: require("./assets/jogos/bosnia and herzegovina.png"),
};
